config:
  chunk_store_config:
    max_look_back_period: 336h
  table_manager:
    retention_deletes_enabled: true
    retention_period: 336h
  limits_config:
    ingestion_rate_mb: 8
    ingestion_burst_size_mb: 16

persistence:
  enabled: true
  size: 16Gi
  storageClassName: default

service:
  type: ClusterIP
  port: 80
  targetPort: 3100

updateStrategy:
  type: OnDelete
