---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus-app02-arrowdemo-xyz
  namespace: monitoring-system
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`prometheus.app02.arrowdemo.xyz`)
    kind: Rule
    services:
    - name: prometheus
      port: 80
  tls:
    certResolver: default

